<script lang="ts">
  import { MapPin, Hammer, Rocket, TrendingUp, Target } from "lucide-svelte";

  export let venture: {
    id: string;
    uid: string;
    name: string;
    slug: string;
    type: string;
    about: string;
    location: string;
    stage: string;          
    seeking: string[] | string;     
    logo_url: string | null;
  };

  /* --------------------------------------------
     Normalize stage 
  -------------------------------------------- */
  const normalizedStage = venture.stage?.toLowerCase();

  const stageMap = {
    starting: {
      icon: Hammer,
      label: "Starting",
      color: "bg-yellow-100 text-yellow-700"
    },
    building: {
      icon: Rocket,
      label: "Building",
      color: "bg-green-100 text-green-700"
    },
    growing: {
      icon: TrendingUp,
      label: "Growing",
      color: "bg-blue-100 text-blue-700"
    }
  };

  /* --------------------------------------------
     Normalize seeking list (array OR string → array)
  -------------------------------------------- */
  let seekingList: string[] = [];

  $: {
    if (Array.isArray(venture.seeking)) {
      seekingList = venture.seeking;
    } else if (typeof venture.seeking === "string") {
      try {
        seekingList = JSON.parse(venture.seeking);
      } catch {
        seekingList = [];
      }
    }
  }

  /* --------------------------------------------
     Seeking badge colors
  -------------------------------------------- */
  const seekingColors: Record<string, string> = {
    collaboration: "bg-yellow-100 text-yellow-700",
    mentorship: "bg-purple-100 text-purple-700",
    investment: "bg-green-100 text-green-700",
    feedback: "bg-blue-100 text-blue-700"
  };

  /* --------------------------------------------
     Title case helper
  -------------------------------------------- */
  function titleCase(str: string): string {
    return str
      ? str.replace(/\w\S*/g, (txt) => txt[0].toUpperCase() + txt.slice(1).toLowerCase())
      : "";
  }

  /* --------------------------------------------
     Initials: 1–2 letters smartly
  -------------------------------------------- */
  function getInitials(name: string) {
    if (!name) return "";
    const words = name.trim().split(" ").filter(Boolean);

    if (words.length >= 2) {
      return (words[0][0] + words[1][0]).toUpperCase();
    }

    const word = words[0];
    return word.substring(0, 2).toUpperCase();
  }

  /* --------------------------------------------
     Deterministic gradient generator
  -------------------------------------------- */
  function hashString(str: string): number {
    let hash = 0;
    for (let i = 0; i < str.length; i++) {
      hash = str.charCodeAt(i) + ((hash << 5) - hash);
    }
    return Math.abs(hash);
  }

  const gradientPalette = [
    ["#6366f1", "#3b82f6"], // indigo → blue
    ["#a855f7", "#ec4899"], // purple → pink
    ["#14b8a6", "#0ea5e9"], // teal → sky blue
    ["#f97316", "#ef4444"], // orange → red
    ["#10b981", "#22c55e"]  // green → emerald
  ];

  function getGradient(name: string) {
    const hash = hashString(name);
    const pair = gradientPalette[hash % gradientPalette.length];
    return `background: linear-gradient(135deg, ${pair[0]}, ${pair[1]});`;
  }
</script>

<a href={`/ventures/${venture.slug}`} class="block">
  <div class="bg-white shadow-md rounded-lg overflow-hidden hover:shadow-lg transition duration-300 flex flex-col cursor-pointer hover:scale-[1.02]">

    <!-- Logo or autogenerated gradient -->
    {#if venture.logo_url}
      <img
        src={venture.logo_url}
        alt={venture.name}
        class="w-full h-48 object-cover"
      />
    {:else}
      <div
        class="w-full h-48 flex items-center justify-center text-white text-4xl font-bold"
        style={getGradient(venture.name)}
      >
        {getInitials(venture.name)}
      </div>
    {/if}

    <div class="p-4 flex flex-col flex-1">

      <!-- Name -->
      <h2 class="text-lg font-semibold mb-1">{venture.name}</h2>

      <!-- Type -->
      <p class="text-blue-600 text-sm font-medium mb-1">
        {titleCase(venture.type)}
      </p>

      <!-- Location -->
      <p class="text-gray-500 text-xs mb-3 flex items-center gap-1">
        <MapPin class="w-3 h-3" />
        {titleCase(venture.location)}
      </p>

      <!-- About -->
      <p class="text-gray-700 mb-3 flex-1 line-clamp-3">
        {venture.about}
      </p>

      <!-- Badges -->
      <div class="flex flex-wrap gap-2 mt-auto">

        <!-- Stage badge -->
        {#if stageMap[normalizedStage]}
          <span
            class={`inline-flex items-center gap-1 px-2 py-1 text-xs rounded-full font-medium ${stageMap[normalizedStage].color}`}
          >
            <svelte:component this={stageMap[normalizedStage].icon} class="w-3 h-3" />
            {stageMap[normalizedStage].label}
          </span>
        {/if}

        <!-- Seeking badges -->
        {#each seekingList as s}
          <span
            class={`inline-flex items-center gap-1 px-2 py-1 text-xs rounded-full font-medium ${
              seekingColors[s.toLowerCase()] ?? "bg-gray-200 text-gray-700"
            }`}
          >
            <Target class="w-3 h-3" />
            {titleCase(s)}
          </span>
        {/each}

      </div>
    </div>
  </div>
</a>
